"""Add is_competition_locked to Tournament

Revision ID: 120ba1757fc2
Revises: 9147c65c61ca
Create Date: 2026-09-23 02:35:10.528693

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120ba1757fc2'
down_revision: Union[str, None] = '9147c65c61ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_competition_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_competition_locked')
    # ### end Alembic commands ###
