"""add_match_participants_for_scramble

Revision ID: 1c09cac2307d
Revises: 951fe524c3d8
Create Date: 2026-09-21 18:54:38.495806

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c09cac2307d'
down_revision: Union[str, None] = '951fe524c3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_membership_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('partner_slot', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_membership_id'], ['club_player_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_membership_id', name='uq_match_participants_match_player'),
    sa.UniqueConstraint('match_id', 'side', 'partner_slot', name='uq_match_participants_match_side_slot')
    )
    op.create_index(op.f('ix_match_participants_id'), 'match_participants', ['id'], unique=False)
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_player_membership_id'), 'match_participants', ['player_membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_participants_player_membership_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_id'), table_name='match_participants')
    op.drop_table('match_participants')
    # ### end Alembic commands ###
