"""add_membership_plans_and_subscriptions_phase12

Revision ID: 1fbc3bc16ba8
Revises: fcf84d85ed63
Create Date: 2026-09-21 22:59:00.887362

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fbc3bc16ba8'
down_revision: Union[str, None] = 'fcf84d85ed63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='plan_status'), nullable=False),
    sa.Column('duration_unit', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='plan_duration_unit'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('booking_limit', sa.Integer(), nullable=True),
    sa.Column('advance_booking_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plans_club_id'), 'membership_plans', ['club_id'], unique=False)
    op.create_index(op.f('ix_membership_plans_id'), 'membership_plans', ['id'], unique=False)
    op.create_index(op.f('ix_membership_plans_status'), 'membership_plans', ['status'], unique=False)
    op.create_table('member_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('player_membership_id', sa.UUID(), nullable=False),
    sa.Column('membership_plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscription_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_plan_id'], ['membership_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_membership_id'], ['club_player_memberships.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_subscriptions_club_id'), 'member_subscriptions', ['club_id'], unique=False)
    op.create_index(op.f('ix_member_subscriptions_id'), 'member_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_member_subscriptions_membership_plan_id'), 'member_subscriptions', ['membership_plan_id'], unique=False)
    op.create_index(op.f('ix_member_subscriptions_player_membership_id'), 'member_subscriptions', ['player_membership_id'], unique=False)
    op.create_index(op.f('ix_member_subscriptions_status'), 'member_subscriptions', ['status'], unique=False)

    # ─── PostgreSQL partial unique index (Phase 12) ───────────────────────────
    # Prevents more than one active or scheduled subscription per player per club.
    # Partial index only applies when status IN ('ACTIVE', 'SCHEDULED').
    # Falls back to a non-partial index on SQLite (used in tests) — service layer
    # enforces the constraint programmatically in that case.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("""
            CREATE UNIQUE INDEX uq_member_subscriptions_one_active_per_player
            ON member_subscriptions (player_membership_id, club_id)
            WHERE status IN ('ACTIVE', 'SCHEDULED');
        """)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS uq_member_subscriptions_one_active_per_player;")
    op.drop_index(op.f('ix_member_subscriptions_status'), table_name='member_subscriptions')
    op.drop_index(op.f('ix_member_subscriptions_player_membership_id'), table_name='member_subscriptions')
    op.drop_index(op.f('ix_member_subscriptions_membership_plan_id'), table_name='member_subscriptions')
    op.drop_index(op.f('ix_member_subscriptions_id'), table_name='member_subscriptions')
    op.drop_index(op.f('ix_member_subscriptions_club_id'), table_name='member_subscriptions')
    op.drop_table('member_subscriptions')
    op.drop_index(op.f('ix_membership_plans_status'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_id'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_club_id'), table_name='membership_plans')
    op.drop_table('membership_plans')
    # ### end Alembic commands ###

