"""add_lessons_and_coaching_phase15

Revision ID: 2d6c44970d50
Revises: 709bc088fe28
Create Date: 2026-09-22 00:38:09.107883

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6c44970d50'
down_revision: Union[str, None] = '709bc088fe28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_club_id'), 'coaches', ['club_id'], unique=False)
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_index(op.f('ix_coaches_is_active'), 'coaches', ['is_active'], unique=False)
    op.create_index(op.f('ix_coaches_user_id'), 'coaches', ['user_id'], unique=False)
    op.create_table('lesson_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_types_club_id'), 'lesson_types', ['club_id'], unique=False)
    op.create_index(op.f('ix_lesson_types_id'), 'lesson_types', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_types_is_active'), 'lesson_types', ['is_active'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('lesson_type_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='lesson_status'), nullable=False),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_type_id'], ['lesson_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_club_id'), 'lessons', ['club_id'], unique=False)
    op.create_index(op.f('ix_lessons_coach_id'), 'lessons', ['coach_id'], unique=False)
    op.create_index(op.f('ix_lessons_court_id'), 'lessons', ['court_id'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_type_id'), 'lessons', ['lesson_type_id'], unique=False)
    op.create_index(op.f('ix_lessons_start_at'), 'lessons', ['start_at'], unique=False)
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.create_table('lesson_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'CANCELLED', 'ATTENDED', 'NO_SHOW', name='lesson_registration_status'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_registrations_id'), 'lesson_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_registrations_lesson_id'), 'lesson_registrations', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_registrations_status'), 'lesson_registrations', ['status'], unique=False)
    op.create_index(op.f('ix_lesson_registrations_user_id'), 'lesson_registrations', ['user_id'], unique=False)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("""
            CREATE UNIQUE INDEX uq_lesson_registrations_one_active_per_user
            ON lesson_registrations (lesson_id, user_id)
            WHERE status != 'CANCELLED';
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS uq_lesson_registrations_one_active_per_user;")
    op.drop_index(op.f('ix_lesson_registrations_user_id'), table_name='lesson_registrations')
    op.drop_index(op.f('ix_lesson_registrations_status'), table_name='lesson_registrations')
    op.drop_index(op.f('ix_lesson_registrations_lesson_id'), table_name='lesson_registrations')
    op.drop_index(op.f('ix_lesson_registrations_id'), table_name='lesson_registrations')
    op.drop_table('lesson_registrations')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_start_at'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson_type_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_court_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_coach_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_club_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_lesson_types_is_active'), table_name='lesson_types')
    op.drop_index(op.f('ix_lesson_types_id'), table_name='lesson_types')
    op.drop_index(op.f('ix_lesson_types_club_id'), table_name='lesson_types')
    op.drop_table('lesson_types')
    op.drop_index(op.f('ix_coaches_user_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_is_active'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_club_id'), table_name='coaches')
    op.drop_table('coaches')
    # ### end Alembic commands ###
