"""add_competition_scheduling_phase17

Revision ID: 3a8e91c7f0b2
Revises: 2d6c44970d50
Create Date: 2026-09-22 01:25:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8e91c7f0b2'
down_revision: Union[str, None] = '2d6c44970d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('court_id', sa.UUID(), nullable=True))
    op.add_column('matches', sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_matches_court_id'), 'matches', ['court_id'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_start_at'), 'matches', ['scheduled_start_at'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_end_at'), 'matches', ['scheduled_end_at'], unique=False)
    op.create_foreign_key('fk_matches_court_id_courts', 'matches', 'courts', ['court_id'], ['id'], ondelete='SET NULL')

    # ─── PostgreSQL Concurrency Exclusion Constraint (Phase 17) ──────────────
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
        op.execute("""
            ALTER TABLE matches
            ADD CONSTRAINT uq_matches_court_no_overlap
            EXCLUDE USING gist (
                court_id WITH =,
                tstzrange(scheduled_start_at, scheduled_end_at, '[)') WITH &&
            )
            WHERE (status != 'CANCELLED' AND court_id IS NOT NULL AND scheduled_start_at IS NOT NULL AND scheduled_end_at IS NOT NULL);
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE matches DROP CONSTRAINT IF EXISTS uq_matches_court_no_overlap;")

    op.drop_constraint('fk_matches_court_id_courts', 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_scheduled_end_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_scheduled_start_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_court_id'), table_name='matches')
    op.drop_column('matches', 'scheduled_end_at')
    op.drop_column('matches', 'scheduled_start_at')
    op.drop_column('matches', 'court_id')
    # ### end Alembic commands ###
