"""add_tournament_and_tournament_registration

Revision ID: 50ef113789d6
Revises: 75e6ab04b3c7
Create Date: 2026-09-21 15:46:30.966148

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ef113789d6'
down_revision: Union[str, None] = '75e6ab04b3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tournament_status'), nullable=False),
    sa.Column('format', sa.Enum('ROUND_ROBIN', 'POOL_PLAY', 'SCRAMBLE', 'BRACKET', name='tournament_format'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='tournament_visibility'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('min_participants', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('scoring_rules', sa.JSON(), nullable=False),
    sa.Column('tiebreaker_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_club_id'), 'tournaments', ['club_id'], unique=False)
    op.create_index(op.f('ix_tournaments_created_by_user_id'), 'tournaments', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_tournaments_format'), 'tournaments', ['format'], unique=False)
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_index(op.f('ix_tournaments_visibility'), 'tournaments', ['visibility'], unique=False)
    op.create_table('tournament_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('player_membership_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'WAITLISTED', 'CANCELLED', name='registration_status'), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_membership_id'], ['club_player_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_membership_id', name='uq_tournament_registrations_tournament_player')
    )
    op.create_index(op.f('ix_tournament_registrations_id'), 'tournament_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_registrations_player_membership_id'), 'tournament_registrations', ['player_membership_id'], unique=False)
    op.create_index(op.f('ix_tournament_registrations_status'), 'tournament_registrations', ['status'], unique=False)
    op.create_index(op.f('ix_tournament_registrations_tournament_id'), 'tournament_registrations', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_registrations_tournament_id'), table_name='tournament_registrations')
    op.drop_index(op.f('ix_tournament_registrations_status'), table_name='tournament_registrations')
    op.drop_index(op.f('ix_tournament_registrations_player_membership_id'), table_name='tournament_registrations')
    op.drop_index(op.f('ix_tournament_registrations_id'), table_name='tournament_registrations')
    op.drop_table('tournament_registrations')
    op.drop_index(op.f('ix_tournaments_visibility'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_format'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_created_by_user_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_club_id'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
