"""add_uq_club_memberships_user_club

Revision ID: 6c8791697921
Revises: 2086c2e0ada8
Create Date: 2026-09-21 15:05:37.356005

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8791697921'
down_revision: Union[str, None] = '2086c2e0ada8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_club_memberships_user_club', 'club_memberships', ['user_id', 'club_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_club_memberships_user_club', 'club_memberships', type_='unique')
    # ### end Alembic commands ###
