"""add_player_profile_and_club_player_membership

Revision ID: 75e6ab04b3c7
Revises: 6c8791697921
Create Date: 2026-09-21 15:26:44.020328

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e6ab04b3c7'
down_revision: Union[str, None] = '6c8791697921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_player_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('membership_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'EXPIRED', name='player_membership_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'club_id', name='uq_club_player_memberships_user_club')
    )
    op.create_index(op.f('ix_club_player_memberships_club_id'), 'club_player_memberships', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_player_memberships_id'), 'club_player_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_club_player_memberships_user_id'), 'club_player_memberships', ['user_id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1000), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_profiles_id'), 'player_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_player_profiles_user_id'), 'player_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_profiles_user_id'), table_name='player_profiles')
    op.drop_index(op.f('ix_player_profiles_id'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_club_player_memberships_user_id'), table_name='club_player_memberships')
    op.drop_index(op.f('ix_club_player_memberships_id'), table_name='club_player_memberships')
    op.drop_index(op.f('ix_club_player_memberships_club_id'), table_name='club_player_memberships')
    op.drop_table('club_player_memberships')
    # ### end Alembic commands ###
