"""add maintenance blocked booking types

Revision ID: 9147c65c61ca
Revises: 3a8e91c7f0b2
Create Date: 2026-09-23 00:01:17.032507

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9147c65c61ca'
down_revision: Union[str, None] = '3a8e91c7f0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE booking_type ADD VALUE IF NOT EXISTS 'maintenance'")
    op.execute("ALTER TYPE booking_type ADD VALUE IF NOT EXISTS 'blocked'")
    op.alter_column('bookings', 'player_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'player_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
