"""add_pools_pool_teams_and_pool_play_match_columns

Revision ID: 951fe524c3d8
Revises: f8a4c7727c77
Create Date: 2026-09-21 18:01:17.890782

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951fe524c3d8'
down_revision: Union[str, None] = 'f8a4c7727c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'display_order', name='uq_pools_tournament_display_order'),
    sa.UniqueConstraint('tournament_id', 'name', name='uq_pools_tournament_name')
    )
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    op.create_index(op.f('ix_pools_tournament_id'), 'pools', ['tournament_id'], unique=False)
    op.create_table('pool_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'team_id', name='uq_pool_teams_pool_team'),
    sa.UniqueConstraint('team_id', name='uq_pool_teams_team')
    )
    op.create_index(op.f('ix_pool_teams_id'), 'pool_teams', ['id'], unique=False)
    op.create_index(op.f('ix_pool_teams_pool_id'), 'pool_teams', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_teams_team_id'), 'pool_teams', ['team_id'], unique=False)
    match_stage = sa.Enum('POOL', 'CHAMPIONSHIP', name='match_stage')
    match_stage.create(op.get_bind(), checkfirst=True)
    op.add_column('matches', sa.Column('stage', match_stage, nullable=True))
    op.add_column('matches', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.add_column('matches', sa.Column('bracket_round', sa.SmallInteger(), nullable=True))
    op.add_column('matches', sa.Column('bracket_position', sa.SmallInteger(), nullable=True))
    op.add_column('matches', sa.Column('next_match_id', sa.UUID(), nullable=True))
    op.add_column('matches', sa.Column('next_match_slot', sa.String(length=10), nullable=True))
    op.alter_column('matches', 'team_a_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('matches', 'team_b_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_matches_next_match_id'), 'matches', ['next_match_id'], unique=False)
    op.create_index(op.f('ix_matches_pool_id'), 'matches', ['pool_id'], unique=False)
    op.create_index(op.f('ix_matches_stage'), 'matches', ['stage'], unique=False)
    op.create_foreign_key('fk_matches_next_match_id', 'matches', 'matches', ['next_match_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_matches_pool_id', 'matches', 'pools', ['pool_id'], ['id'], ondelete='SET NULL')
    op.add_column('tournaments', sa.Column('format_configuration', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'format_configuration')
    op.drop_constraint('fk_matches_next_match_id', 'matches', type_='foreignkey')
    op.drop_constraint('fk_matches_pool_id', 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_stage'), table_name='matches')
    op.drop_index(op.f('ix_matches_pool_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_next_match_id'), table_name='matches')
    op.alter_column('matches', 'team_b_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('matches', 'team_a_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('matches', 'next_match_slot')
    op.drop_column('matches', 'next_match_id')
    op.drop_column('matches', 'bracket_position')
    op.drop_column('matches', 'bracket_round')
    op.drop_column('matches', 'pool_id')
    op.drop_column('matches', 'stage')
    op.drop_index(op.f('ix_pool_teams_team_id'), table_name='pool_teams')
    op.drop_index(op.f('ix_pool_teams_pool_id'), table_name='pool_teams')
    op.drop_index(op.f('ix_pool_teams_id'), table_name='pool_teams')
    op.drop_table('pool_teams')
    op.drop_index(op.f('ix_pools_tournament_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_table('pools')
    match_stage = sa.Enum('POOL', 'CHAMPIONSHIP', name='match_stage')
    match_stage.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
