"""add_player_profile_gender_and_skill

Revision ID: 99f115e543e9
Revises: a1b2c3d4e5f6
Create Date: 2026-09-27 17:50:04.739434

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f115e543e9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    tables = insp.get_table_names()
    if 'tournament_favorites' not in tables:
        op.create_table(
            'tournament_favorites',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('tournament_id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id', 'tournament_id', name='uq_user_tournament_favorite'),
        )
        op.create_index(op.f('ix_tournament_favorites_tournament_id'), 'tournament_favorites', ['tournament_id'], unique=False)
        op.create_index(op.f('ix_tournament_favorites_user_id'), 'tournament_favorites', ['user_id'], unique=False)

    cols = [c['name'] for c in insp.get_columns('player_profiles')]
    if 'gender' not in cols:
        op.add_column('player_profiles', sa.Column('gender', sa.String(length=50), nullable=True))
    if 'skill_rating' not in cols:
        op.add_column('player_profiles', sa.Column('skill_rating', sa.Float(), nullable=True))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_profiles', 'skill_rating')
    op.drop_column('player_profiles', 'gender')
    op.create_index(op.f('ix_matches_tournament_status'), 'matches', ['tournament_id', 'status'], unique=False)
    op.create_index(op.f('ix_matches_tournament_stage'), 'matches', ['tournament_id', 'stage'], unique=False)
    op.drop_index(op.f('ix_tournament_favorites_user_id'), table_name='tournament_favorites')
    op.drop_index(op.f('ix_tournament_favorites_tournament_id'), table_name='tournament_favorites')
    op.drop_table('tournament_favorites')
    # ### end Alembic commands ###
