"""add_league_models_and_competition_fields

Revision ID: a159a18e7b99
Revises: 1c09cac2307d
Create Date: 2026-09-21 20:44:11.091648

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a159a18e7b99'
down_revision: Union[str, None] = '1c09cac2307d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'IN_PROGRESS', 'PLAYOFFS', 'COMPLETED', 'CANCELLED', name='league_status'), nullable=False),
    sa.Column('number_of_weeks', sa.SmallInteger(), nullable=False),
    sa.Column('current_week', sa.SmallInteger(), nullable=False),
    sa.Column('team_size', sa.SmallInteger(), nullable=False),
    sa.Column('playoff_team_count', sa.SmallInteger(), nullable=False),
    sa.Column('scoring_rules', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('champion_team_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_club_id'), 'leagues', ['club_id'], unique=False)
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_status'), 'leagues', ['status'], unique=False)
    op.create_table('league_weeks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('week_type', sa.Enum('REGULAR_SEASON', 'PLAYOFFS', name='league_week_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='league_week_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'week_number', name='uq_league_weeks_league_number')
    )
    op.create_index(op.f('ix_league_weeks_id'), 'league_weeks', ['id'], unique=False)
    op.create_index(op.f('ix_league_weeks_league_id'), 'league_weeks', ['league_id'], unique=False)
    op.create_table('league_weekly_standings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('league_week_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('matches_played', sa.SmallInteger(), nullable=False),
    sa.Column('wins', sa.SmallInteger(), nullable=False),
    sa.Column('losses', sa.SmallInteger(), nullable=False),
    sa.Column('points_scored', sa.Integer(), nullable=False),
    sa.Column('points_allowed', sa.Integer(), nullable=False),
    sa.Column('points_differential', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_week_id'], ['league_weeks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_week_id', 'team_id', name='uq_league_weekly_standings_week_team')
    )
    op.create_index(op.f('ix_league_weekly_standings_id'), 'league_weekly_standings', ['id'], unique=False)
    op.create_index(op.f('ix_league_weekly_standings_league_id'), 'league_weekly_standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_weekly_standings_league_week_id'), 'league_weekly_standings', ['league_week_id'], unique=False)
    op.create_index(op.f('ix_league_weekly_standings_team_id'), 'league_weekly_standings', ['team_id'], unique=False)
    op.add_column('matches', sa.Column('league_id', sa.UUID(), nullable=True))
    op.add_column('matches', sa.Column('league_week_id', sa.UUID(), nullable=True))
    op.alter_column('matches', 'tournament_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_index(op.f('ix_matches_league_week_id'), 'matches', ['league_week_id'], unique=False)
    op.create_foreign_key('fk_matches_league_week_id', 'matches', 'league_weeks', ['league_week_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_matches_league_id', 'matches', 'leagues', ['league_id'], ['id'], ondelete='CASCADE')
    op.add_column('teams', sa.Column('league_id', sa.UUID(), nullable=True))
    op.alter_column('teams', 'tournament_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_unique_constraint('uq_teams_league_name', 'teams', ['league_id', 'name'])
    op.create_foreign_key('fk_teams_league_id', 'teams', 'leagues', ['league_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_teams_league_id', 'teams', type_='foreignkey')
    op.drop_constraint('uq_teams_league_name', 'teams', type_='unique')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.alter_column('teams', 'tournament_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('teams', 'league_id')
    op.drop_constraint('fk_matches_league_week_id', 'matches', type_='foreignkey')
    op.drop_constraint('fk_matches_league_id', 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_league_week_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.alter_column('matches', 'tournament_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('matches', 'league_week_id')
    op.drop_column('matches', 'league_id')
    op.drop_index(op.f('ix_league_weekly_standings_team_id'), table_name='league_weekly_standings')
    op.drop_index(op.f('ix_league_weekly_standings_league_week_id'), table_name='league_weekly_standings')
    op.drop_index(op.f('ix_league_weekly_standings_league_id'), table_name='league_weekly_standings')
    op.drop_index(op.f('ix_league_weekly_standings_id'), table_name='league_weekly_standings')
    op.drop_table('league_weekly_standings')
    op.drop_index(op.f('ix_league_weeks_league_id'), table_name='league_weeks')
    op.drop_index(op.f('ix_league_weeks_id'), table_name='league_weeks')
    op.drop_table('league_weeks')
    op.drop_index(op.f('ix_leagues_status'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_club_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
