"""add_courts_table_phase_10

Revision ID: db1a9c306a27
Revises: c5d312984e1b
Create Date: 2026-09-21 21:56:38.792164

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1a9c306a27'
down_revision: Union[str, None] = 'c5d312984e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('court_number', sa.SmallInteger(), nullable=True),
    sa.Column('surface_type', sa.String(length=50), nullable=True),
    sa.Column('indoor_outdoor', sa.Enum('INDOOR', 'OUTDOOR', 'COVERED', name='court_environment'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='court_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'court_number', name='uq_courts_club_court_number'),
    sa.UniqueConstraint('club_id', 'name', name='uq_courts_club_name')
    )
    op.create_index(op.f('ix_courts_club_id'), 'courts', ['club_id'], unique=False)
    op.create_index(op.f('ix_courts_court_number'), 'courts', ['court_number'], unique=False)
    op.create_index(op.f('ix_courts_display_order'), 'courts', ['display_order'], unique=False)
    op.create_index(op.f('ix_courts_id'), 'courts', ['id'], unique=False)
    op.create_index(op.f('ix_courts_is_active'), 'courts', ['is_active'], unique=False)
    op.create_index(op.f('ix_courts_status'), 'courts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courts_status'), table_name='courts')
    op.drop_index(op.f('ix_courts_is_active'), table_name='courts')
    op.drop_index(op.f('ix_courts_id'), table_name='courts')
    op.drop_index(op.f('ix_courts_display_order'), table_name='courts')
    op.drop_index(op.f('ix_courts_court_number'), table_name='courts')
    op.drop_index(op.f('ix_courts_club_id'), table_name='courts')
    op.drop_table('courts')
    sa.Enum('ACTIVE', 'INACTIVE', name='court_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum('INDOOR', 'OUTDOOR', 'COVERED', name='court_environment').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
