"""add_bookings_table_phase_11

Revision ID: fcf84d85ed63
Revises: db1a9c306a27
Create Date: 2026-09-21 22:18:59.896422

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf84d85ed63'
down_revision: Union[str, None] = 'db1a9c306a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('booked_by_user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'COMPLETED', name='booking_status'), nullable=False),
    sa.Column('booking_type', sa.Enum('PLAYER', 'STAFF', name='booking_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booked_by_user_id'), 'bookings', ['booked_by_user_id'], unique=False)
    op.create_index(op.f('ix_bookings_club_id'), 'bookings', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookings_court_id'), 'bookings', ['court_id'], unique=False)
    op.create_index(op.f('ix_bookings_end_at'), 'bookings', ['end_at'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_player_id'), 'bookings', ['player_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_at'), 'bookings', ['start_at'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.add_column('clubs', sa.Column('opening_time', sa.Time(), server_default='06:00:00', nullable=False))
    op.add_column('clubs', sa.Column('closing_time', sa.Time(), server_default='22:00:00', nullable=False))
    op.add_column('clubs', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))

    # ─── PostgreSQL Concurrency Exclusion Constraint (Phase 11) ──────────────
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
        op.execute("""
            ALTER TABLE bookings
            ADD CONSTRAINT uq_bookings_court_no_overlap
            EXCLUDE USING gist (
                court_id WITH =,
                tstzrange(start_at, end_at, '[)') WITH &&
            )
            WHERE (status = 'CONFIRMED');
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE bookings DROP CONSTRAINT IF EXISTS uq_bookings_court_no_overlap;")

    op.drop_column('clubs', 'timezone')
    op.drop_column('clubs', 'closing_time')
    op.drop_column('clubs', 'opening_time')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_player_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_court_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_club_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booked_by_user_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
