"""Schemas package."""
from app.schemas.auth import AuthResponse, LoginRequest, TokenRefreshRequest, TokenRefreshResponse
from app.schemas.club import ClubResponse, UserClubResponse
from app.schemas.club_membership import (
    AddMemberRequest,
    ClubMembershipDetailResponse,
    MemberResponse,
    MembershipInfo,
    UpdateMemberRequest,
)
from app.schemas.club_player_membership import (
    ClubPlayerMembershipResponse,
    CreateClubPlayerMembershipRequest,
    PlayerClubMembershipDetailResponse,
    PlayerClubResponse,
    UpdateClubPlayerMembershipRequest,
)
from app.schemas.common import TimestampMixin, UUIDMixin
from app.schemas.player_profile import (
    PlayerProfileCreate,
    PlayerProfileResponse,
    PlayerProfileUpdate,
)
from app.schemas.tournament import (
    ScoringRulesSchema,
    TournamentCreate,
    TournamentDiscoveryResponse,
    TournamentResponse,
    TournamentUpdate,
)
from app.schemas.tournament_registration import (
    PlayerSelfRegistrationResponse,
    PlayerTournamentRegistrationStatusResponse,
    TournamentRegistrationResponse,
    UpdateRegistrationRequest,
)
from app.schemas.booking import (
    BookingCancelRequest,
    BookingCourtInfo,
    BookingCreateRequest,
    BookingPlayerInfo,
    BookingResponse,
    ClubAvailabilityResponse,
    CourtAvailability,
    StaffBookingCreateRequest,
    TimeSlotAvailability,
)
from app.schemas.membership import (
    CancelSubscriptionRequest,
    CreateMembershipPlanRequest,
    CreateSubscriptionRequest,
    MembershipPlanDetailResponse,
    MembershipPlanResponse,
    MemberSubscriptionResponse,
    PlayerMembershipView,
    UpdateMembershipPlanRequest,
    UpdateSubscriptionRequest,
)
from app.schemas.payment import (
    CreatePaymentRequest,
    PaymentCancelRequest,
    PaymentFailRequest,
    PaymentResponse,
    PaymentSummaryResponse,
    PlayerPaymentResponse,
)
from app.schemas.event import (
    EventCreateRequest,
    EventDetailResponse,
    EventRegistrationResponse,
    EventResponse,
    EventUpdateRequest,
    PlayerEventDetailResponse,
    PlayerRegisterRequest,
    StaffRegisterPlayerRequest,
)
from app.schemas.lesson import (
    CoachCreateRequest,
    CoachResponse,
    CoachUpdateRequest,
    LessonCreateRequest,
    LessonDetailResponse,
    LessonRegistrationResponse,
    LessonResponse,
    LessonTypeCreateRequest,
    LessonTypeResponse,
    LessonTypeUpdateRequest,
    LessonUpdateRequest,
    PlayerLessonDetailResponse,
)
from app.schemas.scheduling import (
    CourtAvailabilityResponse,
    CourtScheduleResponse,
    CourtSlotAvailability,
    PlayerMatchScheduleResponse,
    RescheduleMatchRequest,
    ScheduleMatchRequest,
    ScheduledMatchResponse,
)
from app.schemas.user import UserResponse

__all__ = [
    "AddMemberRequest",
    "AuthResponse",
    "BookingCancelRequest",
    "BookingCourtInfo",
    "BookingCreateRequest",
    "BookingPlayerInfo",
    "BookingResponse",
    "CancelSubscriptionRequest",
    "ClubAvailabilityResponse",
    "ClubMembershipDetailResponse",
    "ClubPlayerMembershipResponse",
    "ClubResponse",
    "CoachCreateRequest",
    "CoachResponse",
    "CoachUpdateRequest",
    "CourtAvailability",
    "CourtAvailabilityResponse",
    "CourtScheduleResponse",
    "CourtSlotAvailability",
    "CreateClubPlayerMembershipRequest",
    "CreateMembershipPlanRequest",
    "CreateSubscriptionRequest",
    "EventCreateRequest",
    "EventDetailResponse",
    "EventRegistrationResponse",
    "EventResponse",
    "EventUpdateRequest",
    "LessonCreateRequest",
    "LessonDetailResponse",
    "LessonRegistrationResponse",
    "LessonResponse",
    "LessonTypeCreateRequest",
    "LessonTypeResponse",
    "LessonTypeUpdateRequest",
    "LessonUpdateRequest",
    "LoginRequest",
    "MemberResponse",
    "MemberSubscriptionResponse",
    "MembershipInfo",
    "MembershipPlanDetailResponse",
    "MembershipPlanResponse",
    "PaymentCancelRequest",
    "PaymentFailRequest",
    "PaymentResponse",
    "PaymentSummaryResponse",
    "PlayerClubMembershipDetailResponse",
    "PlayerPaymentResponse",
    "PlayerClubResponse",
    "PlayerEventDetailResponse",
    "PlayerLessonDetailResponse",
    "PlayerMatchScheduleResponse",
    "PlayerMembershipView",
    "PlayerProfileCreate",
    "PlayerProfileResponse",
    "PlayerProfileUpdate",
    "PlayerRegisterRequest",
    "PlayerSelfRegistrationResponse",
    "RescheduleMatchRequest",
    "ScheduleMatchRequest",
    "ScheduledMatchResponse",
    "ScoringRulesSchema",
    "StaffBookingCreateRequest",
    "StaffRegisterPlayerRequest",
    "TimeSlotAvailability",
    "TimestampMixin",
    "TokenRefreshRequest",
    "TokenRefreshResponse",
    "TournamentCreate",
    "TournamentDiscoveryResponse",
    "TournamentRegistrationResponse",
    "TournamentResponse",
    "TournamentUpdate",
    "UUIDMixin",
    "UpdateClubPlayerMembershipRequest",
    "UpdateMemberRequest",
    "UpdateMembershipPlanRequest",
    "UpdateSubscriptionRequest",
    "UpdateRegistrationRequest",
    "UserClubResponse",
    "UserResponse",
]

